"""empty message

Revision ID: 394754d0fbfd
Revises: a1b9f38ab6f5
Create Date: 2022-08-08 14:00:11.429531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '394754d0fbfd'
down_revision = 'a1b9f38ab6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper4course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True, comment='卷子id'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='课程id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paper4paper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper4paper',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paper_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='卷子id'),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='课程id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('paper4course')
    # ### end Alembic commands ###
