"""empty message

Revision ID: a1b9f38ab6f5
Revises: 6e87edd2509d
Create Date: 2022-08-08 11:16:42.103179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b9f38ab6f5'
down_revision = '6e87edd2509d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise4course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='课程id'),
    sa.Column('exercise_id', sa.Integer(), nullable=True, comment='题目id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise4paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True, comment='卷子id'),
    sa.Column('exercise_id', sa.Integer(), nullable=True, comment='题目id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('big_title', sa.String(length=1024), nullable=True, comment='大标题题目'),
    sa.Column('small_title', sa.String(length=512), nullable=True, comment='小标题题目'),
    sa.Column('answer', sa.String(length=512), nullable=True, comment='答案'),
    sa.Column('title_type', sa.Integer(), nullable=True, comment='{1:选择，2：填空，3：阅读理解}'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True, comment='卷名'),
    sa.Column('paper_total', sa.Integer(), nullable=True, comment='卷子总分'),
    sa.Column('choice_total', sa.Integer(), nullable=True, comment='选择题总分'),
    sa.Column('write_total', sa.Integer(), nullable=True, comment='填空总分'),
    sa.Column('read_total', sa.Integer(), nullable=True, comment='阅读理解总分'),
    sa.Column('choice_num', sa.Integer(), nullable=True, comment='选择题数量'),
    sa.Column('write_num', sa.Integer(), nullable=True, comment='填空数量'),
    sa.Column('read_num', sa.Integer(), nullable=True, comment='阅读理解数量'),
    sa.Column('time_out', sa.Integer(), nullable=True, comment='考试时长 (秒)'),
    sa.Column('time_end', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('status', sa.Integer(), nullable=True, comment='{0:模拟卷，1:正式卷}'),
    sa.Column('money', sa.Integer(), nullable=True, comment='价格'),
    sa.Column('hot_count', sa.Integer(), nullable=True, comment='热度'),
    sa.Column('create_time', sa.Integer(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper4paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True, comment='卷子id'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='课程id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper4paper')
    op.drop_table('paper')
    op.drop_table('exercises')
    op.drop_table('exercise4paper')
    op.drop_table('exercise4course')
    # ### end Alembic commands ###
