"""empty message

Revision ID: b7c1d38b3bd4
Revises: 
Create Date: 2022-07-21 15:24:31.552395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c1d38b3bd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False, comment='用户名'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('password', sa.String(length=16), nullable=False, comment='密码'),
    sa.Column('info', sa.String(length=256), nullable=True, comment='简介'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('status', sa.BOOLEAN(), nullable=True, comment='上线状态'),
    sa.Column('photo', sa.String(length=256), nullable=True, comment='头像'),
    sa.Column('money', sa.Float(precision=5, asdecimal=2), nullable=True, comment='学习币'),
    sa.Column('course_num', sa.Integer(), nullable=True, comment='特色课数量'),
    sa.Column('solo_num', sa.Integer(), nullable=True, comment='一对一课数量'),
    sa.Column('vip', sa.DateTime(), nullable=True, comment='会员'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False, comment='用户名'),
    sa.Column('attention_num', sa.Integer(), nullable=True, comment='关注数量'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('password', sa.String(length=16), nullable=False, comment='密码'),
    sa.Column('info', sa.String(length=256), nullable=True, comment='简介'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('status', sa.BOOLEAN(), nullable=True, comment='上线状态'),
    sa.Column('photo', sa.String(length=256), nullable=True, comment='头像'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('student2teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'teacher_id', name='student2teacher_ids')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student2teacher')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
