"""empty message

Revision ID: ea5dae98bffb
Revises: c1a38a02022b
Create Date: 2022-07-22 10:26:35.270613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5dae98bffb'
down_revision = 'c1a38a02022b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('courseteacher_ids', 'courseteachers', ['courses_id', 'teacher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courseteacher_ids', 'courseteachers', type_='unique')
    # ### end Alembic commands ###
